export const USER_MANAGEMENT_CLIENT = {
  PAGE_TITLE: "Team",
  PAGE_DESCRIPTION: "Manage team roles and building access in Wayfinder.",
  LIST_TITLE: "Team and access",
  LIST_DESC: "Manage who can access your organization and its buildings.",

  SECTION_OWNER: "Owner",
  SECTION_MANAGERS: "Managers",
  SECTION_MEMBERS: "Members",

  SEARCH_LABEL: "Search team members",
  SEARCH_PLACEHOLDER: "Search by name, email, role, or building",
  MEMBER_SINGULAR: "team member",
  MEMBER_PLURAL: "team members",
  NO_SEARCH_RESULTS: "No team members match your search.",
  EMPTY_TITLE: "No team members yet",
  EMPTY_DESC: "Add a manager or member when you are ready to share access.",
  YOUR_ACCOUNT: "You",
  ORGANIZATION_ACCESS: "All buildings",
  BUILDING_ACCESS: "Building access",
  EDIT_ACCESS: "Access settings",

  COLUMN_NAME: "Name",
  COLUMN_ROLE: "Role",
  COLUMN_BUILDINGS: "Buildings",
  COLUMN_ACTIONS: "",

  ROLE_OWNER: "Owner",
  ROLE_MANAGER: "Manager",
  ROLE_MEMBER: "Member",

  NO_BUILDINGS: "No buildings assigned",
  NO_BUILDINGS_AVAILABLE: "No buildings are available to assign yet.",
  MANAGE_BUILDINGS: "Manage buildings",
  MANAGE_BUILDINGS_TITLE: "Assign buildings",
  MANAGE_BUILDINGS_DESC: "Choose which buildings this member can access.",
  SAVE_BUILDINGS: "Save",

  REMOVE_USER: "Remove",
  REMOVE_USER_LABEL: "Remove user",
  REMOVE_TITLE: "Remove user?",
  REMOVE_CONFIRM_PREFIX: "Remove",
  REMOVE_CONFIRM_SUFFIX: "They will lose access to this organization. This cannot be undone.",

  CANCEL: "Cancel",
  SAVING: "Saving...",

  SUCCESS_ROLE_UPDATED: "Role updated.",
  SUCCESS_BUILDINGS_UPDATED: "Buildings updated.",
  SUCCESS_REMOVED: "User removed.",
  SUCCESS_BLOCKED: "User blocked.",
  SUCCESS_UNBLOCKED: "User unblocked.",

  ERROR_UNAUTHORIZED: "You need to be signed in to do that.",
  ERROR_FORBIDDEN: "Only the owner or a manager can manage users.",
  ERROR_UPDATE_FAILED: "Could not update this user. Please try again.",
  ERROR_REMOVE_FAILED: "Could not remove this user. Please try again.",
  ERROR_NOT_FOUND: "This user could not be found.",

  BACK_TO_TEAM: "Back to team",
  BLOCK_USER: "Block",
  UNBLOCK_USER: "Unblock",
  BLOCKED_BADGE: "Blocked",
  BLOCKED_NOTICE: "This user is blocked and can't sign in.",

  INVITE_STATUS_TITLE: "Invite status",
  INVITE_STATUS_INVITED_BY: "Invited by",
  INVITE_STATUS_ACCEPTED_AT: "Accepted",
  INVITE_STATUS_NONE: "No invite history for this account.",
} as const;
