export const USER_MANAGEMENT_CLIENT = {
  PAGE_TITLE: "Team",
  PAGE_DESCRIPTION: "Manage team roles and building access in Wayfinder.",
  LIST_TITLE: "Team and access",
  LIST_DESC: "Manage who can access your organization and its buildings.",
  ADD_USER: "Add user",

  SEARCH_LABEL: "Search team members",
  SEARCH_PLACEHOLDER: "Search by name, email, role, or building",
  MEMBER_SINGULAR: "team member",
  MEMBER_PLURAL: "team members",
  NO_SEARCH_RESULTS: "No team members match your search.",
  EMPTY_TITLE: "No team members yet",
  EMPTY_DESC: "Add a manager or member when you are ready to share access.",
  YOUR_ACCOUNT: "You",
  ORGANIZATION_ACCESS: "All buildings",
  BUILDING_ACCESS: "Building access",
  EDIT_ACCESS: "Access settings",

  COLUMN_NAME: "Name",
  COLUMN_ROLE: "Role",
  COLUMN_BUILDINGS: "Buildings",
  COLUMN_ACTIONS: "",

  ROLE_OWNER: "Owner",
  ROLE_MANAGER: "Manager",
  ROLE_MEMBER: "Member",

  NO_BUILDINGS: "No buildings assigned",
  NO_BUILDINGS_AVAILABLE: "No buildings are available to assign yet.",
  MANAGE_BUILDINGS: "Manage buildings",
  MANAGE_BUILDINGS_TITLE: "Assign buildings",
  MANAGE_BUILDINGS_DESC: "Choose which buildings this member can access.",
  SAVE_BUILDINGS: "Save",

  REMOVE_USER: "Remove",
  REMOVE_USER_LABEL: "Remove user",
  REMOVE_TITLE: "Remove user?",
  REMOVE_CONFIRM_PREFIX: "Remove",
  REMOVE_CONFIRM_SUFFIX: "They will lose access to this organization. This cannot be undone.",

  CREATE_DIALOG_TITLE: "Add a team member",
  CREATE_DIALOG_DESC: "Create their Wayfinder login and choose what they can access.",
  ACCOUNT_DETAILS: "Account details",
  ACCOUNT_DETAILS_DESC: "Use the name and email they will sign in with.",
  ACCESS_DETAILS: "Workspace access",
  ACCESS_DETAILS_DESC: "Set their role and building access.",
  FIELD_NAME_LABEL: "Name",
  FIELD_NAME_PLACEHOLDER: "Full name",
  FIELD_EMAIL_LABEL: "Email",
  FIELD_EMAIL_PLACEHOLDER: "name@organization.com",
  FIELD_PASSWORD_LABEL: "Temporary password",
  FIELD_PASSWORD_PLACEHOLDER: "At least 8 characters",
  FIELD_PASSWORD_DESC: "They can change this after signing in.",
  FIELD_ROLE_LABEL: "Role",
  ROLE_MANAGER_DESC: "Can manage users, buildings, and every floor.",
  ROLE_MEMBER_DESC: "Can work only in assigned buildings.",
  FIELD_BUILDINGS_LABEL: "Buildings",
  FIELD_BUILDINGS_DESC: "Members only see and edit the buildings assigned here.",

  CANCEL: "Cancel",
  CREATE: "Add user",
  CREATING: "Adding...",
  SAVING: "Saving...",

  SUCCESS_CREATED: "User added.",
  SUCCESS_ROLE_UPDATED: "Role updated.",
  SUCCESS_BUILDINGS_UPDATED: "Buildings updated.",
  SUCCESS_REMOVED: "User removed.",

  ERROR_UNAUTHORIZED: "You need to be signed in to do that.",
  ERROR_FORBIDDEN: "Only the owner or a manager can manage users.",
  ERROR_CREATE_FAILED: "Could not add this user. The email may already be in use.",
  ERROR_UPDATE_FAILED: "Could not update this user. Please try again.",
  ERROR_REMOVE_FAILED: "Could not remove this user. Please try again.",

  VALIDATION_NAME_SHORT: "The name is too short.",
  VALIDATION_EMAIL_INVALID: "Please enter a valid email address.",
  VALIDATION_PASSWORD_SHORT: "The password must be at least 8 characters.",
} as const;
