export const EDITOR_UI_TEXT = {
  desktopOnly: {
    description: "Use a laptop or a larger screen to edit this floor map.",
    title: "Editor unavailable on mobile",
  },
  errors: {
    reload: "Reload",
    title: "Unable to load editor",
  },
  leftPanel: {
    tabs: {
      automation: "Automation",
      create: "Create",
      image: "Image",
    },
  },
  inspector: {
    description: "View and edit the selected item.",
    emptyDescription:
      "Click an object, node, or path edge on the canvas to inspect it.",
    emptyTitle: "No element selected",
    title: "Inspector",
  },
  loading: {
    editor: "Loading editor...",
    floor: "Loading floor...",
  },
  objectToolbox: {
    title: "Add to Map",
    description: "Choose an item, then double-click the map to place it.",
    itemHint: (label: string) => `${label}: select, then double-click the map to place.`,
  },
  referencePanel: {
    imageNameFieldLabel: "Image Name",
    attachedStatus: "Attached",
    autoFitHint: "Canvas will resize to match this image since the floor is empty.",
    currentImageFallback: "Current reference image",
    defaultAlt: (floorName: string) => `${floorName} reference image`,
    description: "Line up walls, rooms, and paths while you edit.",
    emptyStatus: "No image",
    error: "Failed to upload reference image.",
    fileFieldLabel: "Image File",
    imageTypeLabel: "Floor plan or sketch",
    noAltFallback: "No name provided",
    readyToUploadPrefix: "Ready to upload:",
    remove: "Remove",
    cancelStaged: "Cancel",
    replaceAction: "Replace Reference Image",
    title: "Reference",
    uploadAction: "Upload Reference Image",
    uploading: "Uploading Image",
    adjust: {
      title: "Adjust",
      moveHint: "Drag the image on the canvas, or use the sliders below.",
      positionX: "Position X",
      positionY: "Position Y",
      rotation: "Rotation",
      zoom: "Zoom",
      opacity: "Opacity",
      fit: "Fit",
      fitFill: "Fill",
      fitCover: "Cover",
      fitContain: "Contain",
      visible: "Show on canvas",
      lock: "Lock reference image",
      lockDescription: "Locks position and appearance changes.",
    },
  },
  smartBuilder: {
    actions: "Actions",
    autoConnect: {
      description: "Connects object nodes to the nearest hallway point.",
      label: "Auto Connect",
    },
    autoNodes: {
      description: "Adds default nodes to eligible objects.",
      label: "Auto Nodes",
    },
    clearPath: "Clear Path",
    enabledDescription: "Adds shortcuts on top of manual editing.",
    enabledLabel: "Enable automation",
    finishHallwayPath: "Finish Hallway Path",
    generateNodes: "Generate Nodes",
    off: "Off",
    on: "On",
    options: "Options",
    queuedPoints: (count: number) =>
      `${count} point${count === 1 ? "" : "s"} queued. Click empty canvas to add more, or finish the path.`,
    queuedPointsEmpty: "In Connect Paths mode, click empty canvas to queue hallway points.",
    subtitle: "Assisted tools",
    summary: "Speeds up node creation, connections, and hallway paths.",
    title: "Automation",
  },
  toolbar: {
    backToDashboard: "Back to building",
    floorPrefix: "Floor",
    modes: {
      node: "Add Path Nodes",
      path: "Connect Paths",
      select: "Select & Place",
    },
    modeHints: {
      node: "Click the map to drop a new path node. Drag existing nodes to reposition them.",
      path: "Click a node, then another, to connect them. Click the same node again to cancel.",
      select: "Drag anything to move, resize, or rotate it. Double-click empty space to place the object picked below.",
    },
    save: "Save Changes",
    saving: "Saving...",
    unsaved: "Unsaved Changes",
  },
} as const;
