export const EDITOR_VIEWPORT_MIN_ZOOM = 0.25;
export const EDITOR_VIEWPORT_MAX_ZOOM = 4;

export const EDITOR_VIEWPORT_WHEEL_ZOOM_FACTOR = 1.08;
export const EDITOR_VIEWPORT_BUTTON_ZOOM_FACTOR = 1.15;

export const EDITOR_VIEWPORT_FIT_PADDING = 96;
export const EDITOR_VIEWPORT_PAN_OVERSCROLL = 88;
export const EDITOR_VIEWPORT_DRAG_THRESHOLD = 6;
