export const DASHBOARD_CLIENT = {
  PAGE_TITLE: "Dashboard",
  PAGE_DESCRIPTION: "Manage your Wayfinder workspace.",
  OVERVIEW_TITLE: "Workspace overview",
  OVERVIEW_DESCRIPTION: "Open the area you want to manage.",
  BUILDINGS_LABEL: "Buildings",
  FLOORS_LABEL: "Floors",
  ROLE_LABEL: "Your role",
  MANAGE_ORGANIZATION: "Organization settings",
  MANAGE_ORGANIZATION_DESC: "Update your organization identity and details.",
  MANAGE_BUILDINGS: "Buildings and floors",
  MANAGE_BUILDINGS_DESC: "Manage buildings, floors, and their indoor maps.",
  MANAGE_USERS: "Team access",
  MANAGE_USERS_DESC: "Control roles and building assignments.",
  MANAGE_PROFILE: "Your profile",
  MANAGE_PROFILE_DESC: "Update your personal details and profile photo.",

  NAV_ORGANIZATION: "Organization",
  NAV_DASHBOARD: "Overview",
  NAV_BUILDINGS: "Buildings",
  NAV_USERS: "Users",
  NAV_PROFILE: "Profile",
  NAV_WORKSPACE: "Workspace",
  LOG_OUT: "Log out",
  LOG_OUT_TITLE: "Log out of Wayfinder?",
  LOG_OUT_DESCRIPTION: "You will need to sign in again to access your dashboard.",
  CANCEL: "Cancel",

  ORG_FALLBACK_NAME: "Your organization",

  ERROR_UNAUTHORIZED: "You need to be signed in to do that.",
} as const;
