export const PROFILE_CLIENT = {
  PAGE_TITLE: "Organization profile",
  PAGE_DESCRIPTION: "Keep the details visitors use to recognize and find your venue up to date.",
  BACK_TO_DASHBOARD: "Back to dashboard",

  BASICS_TITLE: "Organization details",
  BASICS_DESCRIPTION: "Use the name people know and the facility type that fits best.",
  NAME_LABEL: "Organization name",
  TYPE_LABEL: "Facility type",

  CONTACT_TITLE: "Public contact",
  CONTACT_DESCRIPTION: "Add the contact details visitors should use.",
  EMAIL_LABEL: "Email (optional)",
  PHONE_LABEL: "Phone (optional)",
  WEBSITE_LABEL: "Website (optional)",
  EMAIL_PLACEHOLDER: "info@example.com",
  PHONE_PLACEHOLDER: "+1 416 555 0123",
  WEBSITE_PLACEHOLDER: "https://example.com",

  ADDRESS_TITLE: "Visitor address",
  ADDRESS_DESCRIPTION: "Use the entrance address people should navigate to.",
  ADDRESS_LINE_1_LABEL: "Street address (optional)",
  ADDRESS_LINE_2_LABEL: "Unit or building (optional)",
  CITY_LABEL: "City (optional)",
  REGION_LABEL: "Province, state, or region (optional)",
  POSTAL_CODE_LABEL: "Postal or ZIP code (optional)",
  COUNTRY_LABEL: "Country (optional)",

  ACCOUNT_TITLE: "Account",
  ACCOUNT_DESCRIPTION: "This is the account currently managing the organization.",
  SIGNED_IN_AS: "Signed in as",

  SAVE: "Save changes",
  SAVING: "Saving…",
  SAVED: "Organization profile saved.",
  ADDRESS_MISSING: "Visitor address not added",
  ERROR_UNAUTHORIZED: "You need to be signed in to update this profile.",
  ERROR_NO_ORGANIZATION: "No organization is linked to this account.",
  ERROR_UPDATE_FAILED: "Could not save the profile. Please try again.",

  VALIDATION_NAME_SHORT: "Enter at least 2 characters.",
  VALIDATION_NAME_LONG: "Keep the organization name under 80 characters.",
  VALIDATION_TYPE: "Choose a facility type.",
  VALIDATION_EMAIL: "Enter a valid email address.",
  VALIDATION_PHONE: "Keep the phone number under 30 characters.",
  VALIDATION_WEBSITE: "Enter a valid website address.",
  VALIDATION_ADDRESS: "Keep this address line under 120 characters.",
  VALIDATION_LOCATION: "Keep this location under 80 characters.",
  VALIDATION_POSTAL_CODE: "Keep the postal code under 20 characters.",
} as const;
